#Signup
POST https://dev-auth.krgamestudios.com/auth/signup HTTP/1.1
Content-Type: application/json

{
	"email": "example@example.com",
	"username": "Example",
	"password": "helloworld"
}

###

#Login
POST https://dev-auth.krgamestudios.com/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "example@example.com",
	"password": "helloworld"
}

###

#Query data
GET https://dev-auth.krgamestudios.com/auth/account HTTP/1.1
Authorization: Bearer

###

#Logout
DELETE https://dev-auth.krgamestudios.com/auth/logout HTTP/1.1
Authorization: Bearer

{
	"token": ""
}

###

#Refresh
POST https://dev-auth.krgamestudios.com/auth/token HTTP/1.1
Content-Type: application/json

{
	"token": ""
}

###

#Update account data
PATCH https://dev-auth.krgamestudios.com/auth/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
	"contact": "true"
}

###

#Delete account
DELETE https://dev-auth.krgamestudios.com/auth/deletion HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
	"password": "helloworld"
}
